### ISSUE TITLE
提交后一直都是在处理中

### ISSUE THREAD

**Issue by fj9876** [smallfawn/dingdingdang#1]
提交后一直都是在处理中

**Comment by zhaobuxuan2021** [comment]
^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/json/__init__.py", line 293, in load

    return loads(fp.read(),

           ^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads

    return _default_decoder.decode(s)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode

    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode

    raise JSONDecodeError("Expecting value", s, err.value) from None

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

http://192.168.0.231:5800/open/auth/token?client_id=EfXV-sO1M-4i&client_secret=Labo0zgMPyNOoC1XtCx-osmV

[2024-08-25 14:01:31,021] ERROR in app: Exception on request POST /check

Traceback (most recent call last):

  File "/usr/local/lib/python3.12/site-packages/quart/app.py", line 1403, in handle_request

    return await self.full_dispatch_request(request_context)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/quart/app.py", line 1441, in full_dispatch_request

    result = await self.handle_user_exception(error)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/quart/app.py", line 1029, in handle_user_exception

    raise error

  File "/usr/local/lib/python3.12/site-packages/quart/app.py", line 1439, in full_dispatch_request

    result = await self.dispatch_request(request_context)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/quart/app.py", line 1535, in dispatch_request

    return await self.ensure_async(handler)(**request_.view_args)  # type: ignore

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/api.py", line 177, in check

    existing_data = load_from_file(filename)

                    ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/api.py", line 276, in load_from_file

    return json.load(f)

           ^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/json/__init__.py", line 293, in load

    return loads(fp.read(),

           ^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads

    return _default_decoder.decode(s)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode

    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode

    raise JSONDecodeError("Expecting value", s, err.value) from None

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

http://192.168.0.231:5800/open/auth/token?client_id=EfXV-sO1M-4i&client_secret=Labo0zgMPyNOoC1XtCx-osmV

[2024-08-25 14:01:33,173] ERROR in app: Exception on request POST /check

Traceback (most recent call last):

  File "/usr/local/lib/python3.12/site-packages/quart/app.py", line 1403, in handle_request

    return await self.full_dispatch_request(request_context)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/quart/app.py", line 1441, in full_dispatch_request

    result = await self.handle_user_exception(error)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/quart/app.py", line 1029, in handle_user_exception

    raise error

  File "/usr/local/lib/python3.12/site-packages/quart/app.py", line 1439, in full_dispatch_request

    result = await self.dispatch_request(request_context)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/quart/app.py", line 1535, in dispatch_request

    return await self.ensure_async(handler)(**request_.view_args)  # type: ignore

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/api.py", line 177, in check

    existing_data = load_from_file(filename)

                    ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/api.py", line 276, in load_from_file

    return json.load(f)

           ^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/json/__init__.py", line 293, in load

    return loads(fp.read(),

           ^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads

    return _default_decoder.decode(s)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode

    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode

    raise JSONDecodeError("Expecting value", s, err.value) from None

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

登录完成

[2024-08-26 10:32:27 +0000] [10] [INFO] Running on http://0.0.0.0:12345 (CTRL + C to quit)

[2024-08-26 10:34:57 +0000] [8] [INFO] Running on http://0.0.0.0:12345 (CTRL + C to quit)

ls

ls













^C[2024-08-26 10:35:57 +0000] [10] [INFO] Running on http://0.0.0.0:12345 (CTRL + C to quit)

[2024-09-04 13:22:14 +0000] [8] [INFO] Running on http://0.0.0.0:12345 (CTRL + C to quit)

[2024-09-04 14:54:56 +0000] [10] [INFO] Running on http://0.0.0.0:12345 (CTRL + C to quit)

[2024-09-06 18:33:14 +0000] [9] [INFO] Running on http://0.0.0.0:12345 (CTRL + C to quit)

[2024-09-08 04:22:57 +0000] [10] [INFO] Running on http://0.0.0.0:12345 (CTRL + C to quit)

**Comment by zhaobuxuan2021** [comment]
^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/json/__init__.py", line 293, in load

    return loads(fp.read(),

           ^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads

    return _default_decoder.decode(s)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode

    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode

    raise JSONDecodeError("Expecting value", s, err.value) from None

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


[2024-08-25 14:01:31,021] ERROR in app: Exception on request POST /check

Traceback (most recent call last):

  File "/usr/local/lib/python3.12/site-packages/quart/app.py", line 1403, in handle_request

    return await self.full_dispatch_request(request_context)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/quart/app.py", line 1441, in full_dispatch_request

    result = await self.handle_user_exception(error)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/quart/app.py", line 1029, in handle_user_exception

    raise error

  File "/usr/local/lib/python3.12/site-packages/quart/app.py", line 1439, in full_dispatch_request

    result = await self.dispatch_request(request_context)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/quart/app.py", line 1535, in dispatch_request

    return await self.ensure_async(handler)(**request_.view_args)  # type: ignore

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/api.py", line 177, in check

    existing_data = load_from_file(filename)

                    ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/api.py", line 276, in load_from_file

    return json.load(f)

           ^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/json/__init__.py", line 293, in load

    return loads(fp.read(),

           ^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads

    return _default_decoder.decode(s)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode

    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode

    raise JSONDecodeError("Expecting value", s, err.value) from None

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

[2024-08-25 14:01:33,173] ERROR in app: Exception on request POST /check

Traceback (most recent call last):

  File "/usr/local/lib/python3.12/site-packages/quart/app.py", line 1403, in handle_request

    return await self.full_dispatch_request(request_context)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/quart/app.py", line 1441, in full_dispatch_request

    result = await self.handle_user_exception(error)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/quart/app.py", line 1029, in handle_user_exception

    raise error

  File "/usr/local/lib/python3.12/site-packages/quart/app.py", line 1439, in full_dispatch_request

    result = await self.dispatch_request(request_context)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/quart/app.py", line 1535, in dispatch_request

    return await self.ensure_async(handler)(**request_.view_args)  # type: ignore

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/api.py", line 177, in check

    existing_data = load_from_file(filename)

                    ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/api.py", line 276, in load_from_file

    return json.load(f)

           ^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/json/__init__.py", line 293, in load

    return loads(fp.read(),

           ^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads

    return _default_decoder.decode(s)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode

    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode

    raise JSONDecodeError("Expecting value", s, err.value) from None

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

登录完成

[2024-08-26 10:32:27 +0000] [10] [INFO] Running on http://0.0.0.0:12345 (CTRL + C to quit)

[2024-08-26 10:34:57 +0000] [8] [INFO] Running on http://0.0.0.0:12345 (CTRL + C to quit)

ls

ls













^C[2024-08-26 10:35:57 +0000] [10] [INFO] Running on http://0.0.0.0:12345 (CTRL + C to quit)

[2024-09-04 13:22:14 +0000] [8] [INFO] Running on http://0.0.0.0:12345 (CTRL + C to quit)

[2024-09-04 14:54:56 +0000] [10] [INFO] Running on http://0.0.0.0:12345 (CTRL + C to quit)

[2024-09-06 18:33:14 +0000] [9] [INFO] Running on http://0.0.0.0:12345 (CTRL + C to quit)

[2024-09-08 04:22:57 +0000] [10] [INFO] Running on http://0.0.0.0:12345 (CTRL + C to quit)
